const bancoDados = {
    portugues: [
        // --- 1. SÍLABA TÓNICA E CLASSIFICAÇÃO (Agudas, Graves, Esdruxulonas) ---
        { q: "Qual a sílaba tónica de 'Pássaro'?", o: ["Pás", "sa", "ro"], r: 0 },
        { q: "Qual a sílaba tónica de 'Café'?", o: ["Ca", "Fé"], r: 1 },
        { q: "Sílaba tónica de 'Relógio':", o: ["Re", "Ló", "gio"], r: 1 },
        { q: "Sílaba tónica de 'Médico':", o: ["Mé", "di", "co"], r: 0 },
        { q: "Qual a sílaba tónica de 'Computador'?", o: ["Com", "pu", "ta", "dor"], r: 3 },
        { q: "Qual a sílaba tónica de 'Estrela'?", o: ["Es", "tre", "la"], r: 1 },
        { q: "Sílaba tónica de 'Sapato':", o: ["Sa", "pa", "to"], r: 1 },
        { q: "Na palavra 'Menino', a sílaba tónica é 'ni'. As outras são:", o: ["Átonas", "Tónicas também"], r: 0 },
        { q: "A palavra 'Pai' tem quantas sílabas átonas?", o: ["Zero (é monossílaba tónica)", "Uma"], r: 0 },
        { q: "Na palavra 'Sapato', quais são as sílabas átonas?", o: ["'Sa' e 'to'", "'pa'"], r: 0 },
        { q: "A palavra 'Janela' é uma palavra:", o: ["Esdruxulona", "Grave", "Aguda"], r: 1 },
        { q: "A palavra 'Jacaré' é uma palavra:", o: ["Aguda", "Grave"], r: 0 },
        { q: "A palavra 'Lâmpada' é:", o: ["Aguda", "Grave", "Esdruxulona"], r: 2 },
        { q: "A palavra 'Sófá' é:", o: ["Aguda", "Grave"], r: 0 },
        { q: "A palavra 'Pincel' é uma palavra:", o: ["Aguda", "Grave"], r: 0 },
        { q: "A palavra 'Música' é uma palavra:", o: ["Grave", "Esdruxulona"], r: 1 },
        { q: "A palavra 'Rápido' é uma palavra:", o: ["Aguda", "Grave", "Esdruxulona"], r: 2 },
        { q: "A palavra 'Chaminé' é uma palavra:", o: ["Aguda", "Grave"], r: 0 },
        { q: "A palavra 'Caderno' é uma palavra:", o: ["Aguda", "Grave"], r: 1 },
        { q: "A palavra 'Boneca' é uma palavra:", o: ["Aguda", "Grave"], r: 1 },

        // --- 2. DIVISÃO SILÁBICA E NÚMERO DE SÍLABAS ---
        { q: "Como se separa a palavra 'Carro'?", o: ["Ca-rro", "Car-ro"], r: 1 },
        { q: "Como se separa 'Pássaro'?", o: ["Pás-sa-ro", "Páss-a-ro"], r: 0 },
        { q: "Na separação silábica de 'Passarinho', os 'ss' ficam:", o: ["Juntos", "Separados (Pas-sa...)"], r: 1 },
        { q: "Como se separa a palavra 'Passarinho'?", o: ["Pas-sa-ri-nho", "Pa-ssa-ri-nho"], r: 0 },
        { q: "Quantas sílabas tem 'Borboleta'?", o: ["3", "4", "5"], r: 1 },
        { q: "'Sol' é uma palavra:", o: ["Monossílaba", "Dissílaba"], r: 0 },
        { q: "'Escola' é uma palavra:", o: ["Dissílaba", "Trissílaba"], r: 1 },
        { q: "'Hipopótamo' é uma palavra:", o: ["Trissílaba", "Polissílaba"], r: 1 },
        { q: "A palavra 'Felicidade' é:", o: ["Trissílaba", "Polissílaba"], r: 1 },
        { q: "Quantas sílabas tem 'Arco-íris'?", o: ["2", "4"], r: 1 },

        // --- 3. NOMES (Próprios, Comuns, Coletivos) ---
        { q: "A palavra 'Lisboa' é um nome:", o: ["Comum", "Próprio"], r: 1 },
        { q: "Escolha o nome próprio:", o: ["País", "Portugal"], r: 1 },
        { q: "Qual destas palavras é um nome próprio?", o: ["Porto", "Cidade"], r: 0 },
        { q: "Qual nome é próprio?", o: ["Rio", "Douro"], r: 1 },
        { q: "Qual é um nome comum?", o: ["Maria", "Menina"], r: 1 },
        { q: "O coletivo de 'Peixes' é:", o: ["Cardume", "Alcateia"], r: 0 },
        { q: "O coletivo de 'Ovelhas' é:", o: ["Rebanho", "Matilha"], r: 0 },
        { q: "O coletivo de 'Cães' é:", o: ["Matilha", "Alcateia"], r: 0 },
        { q: "O coletivo de 'Livros' é:", o: ["Biblioteca", "Pinacoteca"], r: 0 },

        // --- 4. GÉNERO E NÚMERO (Masculino/Feminino, Plural) ---
        { q: "Feminino de 'Ator':", o: ["Atriz", "Atora"], r: 0 },
        { q: "Feminino de 'Leão' é:", o: ["Leoa", "Leoaia"], r: 0 },
        { q: "Feminino de 'Cavalo'?", o: ["Cavala", "Égua"], r: 1 },
        { q: "Qual o feminino de 'Cão'?", o: ["Cadela", "Cãozinha"], r: 0 },
        { q: "Qual o feminino de 'Doutor'?", o: ["Doutora", "Doutoraia"], r: 0 },
        { q: "Masculino de 'Galinha':", o: ["Frango", "Galo"], r: 1 },
        { q: "O masculino de 'Ovelha' é:", o: ["Carneiro", "Bode"], r: 0 },
        { q: "Feminino de 'Padrinho'?", o: ["Madrinha", "Mãe"], r: 0 },
        { q: "Qual é o masculino de 'Madrinha'?", o: ["Pai", "Padrinho"], r: 1 },
        { q: "Plural de 'Pão':", o: ["Pães", "Pãos"], r: 0 },
        { q: "Plural de 'Animal':", o: ["Animais", "Animales"], r: 0 },
        { q: "Plural de 'Funil':", o: ["Funis", "Funiles"], r: 0 },
        { q: "Plural de 'Nariz'?", o: ["Narizes", "Narizs"], r: 0 },
        { q: "Plural de 'Jardim'?", o: ["Jardims", "Jardins"], r: 1 },
        { q: "Plural de 'Pai'?", o: ["Pais", "Paes"], r: 0 },
        { q: "O plural de 'Jornal' é:", o: ["Jornais", "Jornals"], r: 0 },
        { q: "O plural de 'Botão' é:", o: ["Botões", "Botãos"], r: 0 },
        { q: "Escolha o plural de 'Lençol':", o: ["Lençóis", "Lençols"], r: 0 },
        { q: "Plural de 'Balão' é:", o: ["Balões", "Balãos"], r: 0 },

        // --- 5. ACENTUAÇÃO E SINAIS GRÁFICOS ---
        { q: "Como se chama o sinal (~) em 'Mão'?", o: ["Acento Agudo", "Til"], r: 1 },
        { q: "Como se chama o sinal por baixo da letra 'c' em 'Moça'?", o: ["Til", "Cedilha"], r: 1 },
        { q: "Qual palavra usa o TIL (~)?", o: ["Maçã", "Música"], r: 0 },
        { q: "A palavra 'Mão' usa o til porque o som é:", o: ["Aberto", "Nasal"], r: 1 },
        { q: "'Árvore' tem acento:", o: ["Agudo (´)", "Circunflexo (^)"], r: 0 },
        { q: "O que indica o acento circunflexo?", o: ["Som aberto", "Som fechado"], r: 1 },
        { q: "Qual palavra tem acento circunflexo?", o: ["Lápis", "Ténis"], r: 1 },
        { q: "O que indica o ponto de exclamação (!)?", o: ["Uma pergunta", "Uma surpresa ou ordem"], r: 1 },
        { q: "O ponto de interrogação (?) serve para:", o: ["Fazer uma pergunta", "Dar uma ordem"], r: 0 },
        { q: "O ponto final (.) serve para:", o: ["Terminar uma frase", "Fazer uma pergunta"], r: 0 },

        // --- 6. SEMÂNTICA E GRAMÁTICA (Antónimos, Sinónimos, Verbos) ---
        { q: "Antónimo de 'Fácil':", o: ["Difícil", "Rápido"], r: 0 },
        { q: "Antónimo de 'Quente'?", o: ["Arrefece", "Frio"], r: 1 },
        { q: "Qual o antónimo de 'Baixo'?", o: ["Curto", "Alto"], r: 1 },
        { q: "Qual o antónimo de 'Novo'?", o: ["Velho", "Moderno"], r: 0 },
        { q: "Antónimo de 'Cheio'?", o: ["Vazio", "Grande"], r: 0 },
        { q: "Qual o antónimo de 'Aparecer'?", o: ["Sumir/Desaparecer", "Ficar"], r: 0 },
        { q: "Sinónimo de 'Lindo':", o: ["Feio", "Bonito"], r: 1 },
        { q: "Sinónimo de 'Morar'?", o: ["Viver/Residir", "Sair"], r: 0 },
        { q: "Qual o sinónimo de 'Alegre'?", o: ["Triste", "Contente"], r: 1 },
        { q: "Qual destas palavras é um verbo (ação)?", o: ["Salto", "Saltar"], r: 1 },
        { q: "A frase 'Eu comi' está no:", o: ["Passado", "Futuro"], r: 0 },
        { q: "A frase 'O sol brilha' está no:", o: ["Presente", "Passado"], r: 0 },
        { q: "Na frase 'A Maria comeu a maçã', quem é o sujeito?", o: ["A maçã", "A Maria"], r: 1 },

        // --- 7. LEITURA E ESCRITA ---
        { q: "Qual palavra rima com 'Coração'?", o: ["Mão", "Céu"], r: 0 },
        { q: "Qual destas palavras rima com 'Janela'?", o: ["Panela", "Porta"], r: 0 },
        { q: "Aumentativo de 'Casa'?", o: ["Casinha", "Casarão"], r: 1 },
        { q: "Diminutivo de 'Livro'?", o: ["Livrinho", "Livrote"], r: 0 },
        { q: "Qual é o diminutivo de 'Cão'?", o: ["Cãozão", "Cãozinho"], r: 1 },
        { q: "O que é uma 'resposta de construção'?", o: ["Marcar uma cruz", "Escrever a resposta com as minhas palavras"], r: 1 }
    ],
    matematica: [
        // --- 1. NÚMEROS E OPERAÇÕES (Até 399, Dobro, Metade, Pares/Ímpares) ---
        { q: "Qual número vem logo a seguir ao 398?", o: ["397", "399"], r: 1 },
        { q: "Qual o antecessor de 300?", o: ["299", "301"], r: 0 },
        { q: "Qual o número que vem antes de 399?", o: ["398", "400"], r: 0 },
        { q: "O número 399 é o sucessor de:", o: ["398", "400"], r: 0 },
        { q: "Qual número está entre 250 e 252?", o: ["251", "253"], r: 0 },
        { q: "Qual o número maior?", o: ["309", "390"], r: 1 },
        { q: "Qual o número par?", o: ["122", "123"], r: 0 },
        { q: "O número 200 é:", o: ["Par", "Ímpar"], r: 0 },
        { q: "Qual o número ímpar?", o: ["350", "351"], r: 1 },
        { q: "O dobro de 150 é:", o: ["300", "200"], r: 0 },
        { q: "Qual número é o dobro de 100?", o: ["200", "150"], r: 0 },
        { q: "A metade de 200 é:", o: ["100", "150"], r: 0 },
        { q: "A metade de 100 é:", o: ["25", "50"], r: 1 },
        { q: "Qual é a metade de 20?", o: ["10", "5"], r: 0 },
        { q: "Como se escreve o número ordinal 5º?", o: ["Quinto", "Quarto"], r: 0 },
        { q: "Como se escreve o número ordinal 10º?", o: ["Décimo", "Nono"], r: 0 },

        // --- 2. DECOMPOSIÇÃO E VALOR POSICIONAL ---
        { q: "3 Centenas + 4 Dezenas + 2 Unidades é:", o: ["342", "243"], r: 0 },
        { q: "3 Centenas + 9 Unidades é o número:", o: ["309", "390"], r: 0 },
        { q: "3 Centenas + 5 Unidades é igual a:", o: ["350", "305"], r: 1 },
        { q: "3 centenas e 2 dezenas formam o número:", o: ["320", "302"], r: 0 },
        { q: "O número 382 tem:", o: ["3 Centenas, 8 Dezenas, 2 Unidades", "3 Dezenas, 8 Unidades"], r: 0 },
        { q: "O número 245 tem quantas dezenas?", o: ["4", "2", "5"], r: 0 },
        { q: "Quantas dezenas tem o número 120?", o: ["2", "12"], r: 1 },
        { q: "O número 300 tem quantas dezenas?", o: ["3", "30"], r: 1 },
        { q: "10 dezenas formam:", o: ["1 Unidade", "1 Centena"], r: 1 },
        { q: "O número 100 é uma:", o: ["Dezena", "Centena"], r: 1 },
        { q: "Quantas centenas tem o número 399?", o: ["3", "9"], r: 0 },
        { q: "Trezentos e oitenta e cinco é:", o: ["385", "358"], r: 0 },
        { q: "O número 301 lê-se:", o: ["Trezentos e um", "Duzentos e um"], r: 0 },

        // --- 3. GEOMETRIA E SÓLIDOS (Poliedros e Não Poliedros) ---
        { q: "O poliedro tem apenas superfícies:", o: ["Curvas", "Planas"], r: 1 },
        { q: "Qual destes sólidos geométricos é um poliedro?", o: ["Cubo", "Esfera"], r: 0 },
        { q: "A pirâmide tem faces planas? É um poliedro?", o: ["Sim", "Não"], r: 0 },
        { q: "O paralelepípedo tem faces planas?", o: ["Sim", "Não"], r: 0 },
        { q: "O cubo tem quantas faces?", o: ["6", "8"], r: 0 },
        { q: "Qual sólido tem 12 arestas e 6 faces iguais?", o: ["Cubo", "Esfera"], r: 0 },
        { q: "A esfera é um sólido que:", o: ["Não rola", "Rola (Não Poliedro)"], r: 1 },
        { q: "O cilindro pode rolar. Ele é um:", o: ["Poliedro", "Não Poliedro"], r: 1 },
        { q: "O cone tem uma base redonda. Ele é:", o: ["Poliedro", "Não Poliedro"], r: 1 },
        { q: "Uma pirâmide termina num bico chamado:", o: ["Lado", "Vértice"], r: 1 },
        { q: "Quantos vértices tem um triângulo?", o: ["3", "4"], r: 0 },
        { q: "Um quadrado tem quantos vértices?", o: ["4", "3"], r: 0 },
        { q: "Um retângulo tem quantos lados?", o: ["4", "3"], r: 0 },

        // --- 4. DINHEIRO E MEDIDAS ---
        { q: "Uma moeda de 1€ vale quantos cêntimos?", o: ["50", "100"], r: 1 },
        { q: "Qual moeda tem mais valor?", o: ["20 cêntimos", "50 cêntimos"], r: 1 },
        { q: "Quantas moedas de 50 cent fazem 2€?", o: ["4 moedas", "2 moedas"], r: 0 },
        { q: "Tens 2 moedas de 50 cent. Quanto tens no total?", o: ["1 Euro", "2 Euros"], r: 0 },
        { q: "Uma nota de 10€ e duas de 5€ fazem:", o: ["20€", "15€"], r: 0 },
        { q: "Quanto valem 2 notas de 5€ e 1 moeda de 2€?", o: ["12€", "15€"], r: 0 },
        { q: "Se pagas 2€ por um sumo de 1,50€, qual o troco?", o: ["0,50€", "1,00€"], r: 0 },
        { q: "O que usamos para medir o peso?", o: ["Régua", "Balança"], r: 1 },
        { q: "O que usamos para medir o comprimento?", o: ["Balança", "Régua/Fita Métrica"], r: 1 },

        // --- 5. DADOS E ESTATÍSTICA (Carroll e Frequências) ---

        { q: "O diagrama de Carroll serve para:", o: ["Organizar objetos por duas características", "Somar números"], r: 0 },
        { q: "Num diagrama de Carroll, onde coloco um quadrado azul?", o: ["No grupo 'Quadrados' e 'Azul'", "Só no azul"], r: 0 },
        { q: "Uma tabela de frequências serve para:", o: ["Contar e organizar dados", "Escrever histórias"], r: 0 },
        { q: "Numa tabela, o que representa a 'frequência'?", o: ["O número de vezes que algo acontece", "A cor"], r: 0 },
        { q: "Como se chama o gráfico com barras?", o: ["Gráfico de Barras", "Gráfico de Círculo"], r: 0 },
        { q: "Num gráfico de barras, a barra mais alta representa:", o: ["O valor mais frequente", "O valor menor"], r: 0 },
        { q: "O que é uma 'recolha de dados'?", o: ["Contar e anotar informações", "Apagar tudo"], r: 0 },

        // --- 6. ITINERÁRIOS E DIREÇÃO ---
        { q: "Um itinerário serve para:", o: ["Contar dinheiro", "Descrever um caminho"], r: 1 },
        { q: "Num itinerário, o que significa a seta para cima ↑?", o: ["Virar à esquerda", "Seguir em frente"], r: 1 },
        { q: "Num itinerário, virar 90º à direita é:", o: ["Meia volta", "Quarto de volta"], r: 1 },
        { q: "Num itinerário, o que significa a seta para a esquerda ←?", o: ["Seguir em frente", "Mudar de direção para a esquerda"], r: 1 },
        { q: "Se deres uma volta completa (360º), voltas ao lugar inicial?", o: ["Sim", "Não"], r: 0 },
        { q: "Se andares 3 casas para a direita num mapa, mudaste de:", o: ["Posição", "Tamanho"], r: 0 }
    ],
    estudoMeio: [
        // --- 1. SOCIEDADE, FAMÍLIA E GRUPOS SOCIAIS ---
        { q: "A família e a escola são exemplos de:", o: ["Grupos e comunidades", "Países"], r: 0 },
        { q: "A família nuclear é formada por:", o: ["Pais e Filhos", "Primos e Vizinhos"], r: 0 },
        { q: "Quem faz parte da tua família alargada?", o: ["Tios e Primos", "Colegas de turma"], r: 0 },
        { q: "Os teus pais, irmãos e avós formam a tua:", o: ["Família", "Escola"], r: 0 },
        { q: "O teu apelido (sobrenome) vem da tua:", o: ["Família", "Escola"], r: 0 },
        { q: "Um grupo social onde vivemos é a:", o: ["Comunidade", "Floresta"], r: 0 },
        { q: "A união de várias famílias ou pessoas com interesses comuns forma uma:", o: ["Comunidade", "Equipa"], r: 0 },
        { q: "A escola é um exemplo de grupo:", o: ["Social", "Familiar"], r: 0 },
        { q: "A escola é uma comunidade de:", o: ["Aprendizagem", "Culinária"], r: 0 },
        { q: "Viver em sociedade exige seguir:", o: ["Regras e leis", "Apenas o que queremos"], r: 0 },

        // --- 2. DIREITOS E DEVERES DA CRIANÇA ---
        { q: "Toda a criança tem direito a:", o: ["Saúde e Educação", "Trabalhar"], r: 0 },
        { q: "Qual destes é um direito à identidade?", o: ["Ter um Nome", "Ter um Computador"], r: 0 },
        { q: "Brincar é um:", o: ["Direito", "Dever"], r: 0 },
        { q: "As crianças têm direito a cuidados médicos?", o: ["Sim", "Não"], r: 0 },
        { q: "A educação é um:", o: ["Direito das crianças", "Castigo"], r: 0 },
        { q: "Os direitos das crianças são iguais para todos?", o: ["Sim, em todo o mundo", "Só em Portugal"], r: 0 },
        { q: "Os direitos das crianças estão escritos na:", o: ["Convenção dos Direitos da Criança", "Livro de Matemática"], r: 0 },
        { q: "Um dever da criança na escola é:", o: ["Estudar e respeitar", "Faltar"], r: 0 },
        { q: "Toda a criança tem o dever de:", o: ["Brincar apenas", "Respeitar os outros"], r: 1 },
        { q: "Um exemplo de um dever da criança é:", o: ["Arrumar os brinquedos", "Ter um nome"], r: 0 },

        // --- 3. PASSADO PESSOAL, FAMILIAR E HISTÓRIA ---
        { q: "A árvore genealógica serve para:", o: ["Ver o passado da família", "Contar dinheiro"], r: 0 },
        { q: "Os teus avós são pais dos teus:", o: ["Primos", "Pais"], r: 1 },
        { q: "O passado familiar estuda os nossos:", o: ["Antepassados", "Colegas"], r: 0 },
        { q: "Um exemplo de passado pessoal é:", o: ["O dia em que nasci", "O futuro"], r: 0 },
        { q: "O teu passado pessoal começou quando:", o: ["Nasceste", "Entraste na escola"], r: 0 },
        { q: "O que aprendemos com o passado familiar?", o: ["A nossa origem e história", "O tempo de amanhã"], r: 0 },
        { q: "No passado, Portugal foi visitado por Romanos e Árabes?", o: ["Sim", "Não"], r: 0 },
        { q: "O 25 de Abril celebra a:", o: ["Independência", "Liberdade/Democracia"], r: 1 },
        { q: "A influência de outros povos na nossa cultura vê-se na:", o: ["Comida e língua", "Altura das pessoas"], r: 0 },

        // --- 4. PORTUGAL: LOCALIZAÇÃO E GEOGRAFIA ---
        { q: "Portugal fica situado na:", o: ["Europa", "Ásia"], r: 0 },
        { q: "Portugal está localizado na Península:", o: ["Ibérica", "Itálica"], r: 0 },
        { q: "Qual país faz fronteira terrestre com Portugal?", o: ["França", "Espanha"], r: 1 },
        { q: "O oceano que banha a costa de Portugal chama-se:", o: ["Pacífico", "Atlântico"], r: 1 },
        { q: "Portugal tem quantos arquipélagos?", o: ["2 (Madeira e Açores)", "1"], r: 0 },
        { q: "Onde se localizam os Açores e a Madeira?", o: ["No mar Mediterrâneo", "No oceano Atlântico"], r: 1 },
        { q: "Qual a capital de Portugal?", o: ["Porto", "Lisboa"], r: 1 },
        { q: "Portugal está dividido em vários:", o: ["Distritos e Concelhos", "Países"], r: 0 },
        { q: "Qual o maior rio que nasce em Portugal?", o: ["Mondego", "Tejo"], r: 0 },
        { q: "Qual é a cor do oceano nos mapas?", o: ["Verde", "Azul"], r: 1 },

        // --- 5. SÍMBOLOS, INSTITUIÇÕES E CULTURA ---
        { q: "As cores da bandeira de Portugal são:", o: ["Verde e Vermelho", "Azul e Branco"], r: 0 },
        { q: "A bandeira nacional é um símbolo de:", o: ["Portugal", "Espanha"], r: 0 },
        { q: "Os símbolos nacionais são a Bandeira e o:", o: ["Hino Nacional", "Futebol"], r: 0 },
        { q: "O Hino Nacional chama-se:", o: ["A Portuguesa", "O Fado"], r: 0 },
        { q: "Qual o nome da nossa moeda atual?", o: ["Escudo", "Euro"], r: 1 },
        { q: "Onde vive o Presidente de Portugal?", o: ["Palácio de Belém", "Câmara Municipal"], r: 0 },
        { q: "Quem governa o nosso país?", o: ["O Presidente da República e o Governo", "O Diretor da Escola"], r: 0 },
        { q: "Quem cuida da limpeza da vila ou cidade?", o: ["A Câmara Municipal", "A Escola"], r: 0 },
        { q: "O 10 de Junho é o dia de:", o: ["Portugal, de Camões e das Comunidades", "Natal"], r: 0 },
        { q: "Qual destas é uma tradição portuguesa?", o: ["Cantar o Fado", "Comer Sushi"], r: 0 },

        // --- 6. PATRIMÓNIO E COMUNIDADE ---
        { q: "O que são monumentos?", o: ["Prédios novos", "Construções que contam a história"], r: 1 },
        { q: "Os monumentos servem para:", o: ["Guardar carros", "Preservar a História"], r: 1 },
        { q: "O que é património nacional?", o: ["Bens culturais importantes", "Bens privados"], r: 0 },
        { q: "Um museu é lugar de:", o: ["Lixo", "Cultura"], r: 1 },
        { q: "Qual a função de um museu na comunidade?", o: ["Vender brinquedos", "Guardar a memória e cultura"], r: 1 },
        { q: "Qual o animal símbolo de Barcelos?", o: ["Galo", "Águia"], r: 0 },
        { q: "Devemos respeitar as outras culturas e tradições?", o: ["Sim", "Não"], r: 0 },

        // --- 7. SEGURANÇA, MEIOS E NATUREZA ---
        { q: "Sinais de trânsito servem para:", o: ["Decorar a rua", "Segurança rodoviária"], r: 1 },
        { q: "Para atravessar a rua em segurança usamos:", o: ["Passadeira", "Qualquer lugar"], r: 0 },
        { q: "Qual é um meio de transporte terrestre?", o: ["Comboio", "Avião"], r: 0 },
        { q: "Qual destes é um meio de comunicação?", o: ["Televisão", "Bicicleta"], r: 0 },
        { q: "As plantas para crescerem precisam de:", o: ["Água e Luz", "Sumo"], r: 0 },
        { q: "Devemos proteger a Natureza?", o: ["Sempre", "Nunca"], r: 0 },
        { q: "O lixo azul serve para reciclar:", o: ["Papel", "Vidro"], r: 0 },
        { q: "O lixo verde serve para reciclar:", o: ["Vidro", "Plástico"], r: 0 },
        { q: "O lixo amarelo serve para reciclar:", o: ["Plástico e Metal", "Papel"], r: 0 }
    ]
};