const bancoDados = {
    portugues: [
        // --- 1. SÍLABA TÓNICA E CLASSIFICAÇÃO (Agudas, Graves, Esdruxulares) ---
        { q: "Qual a sílaba tónica de 'Pássaro'?", o: ["Pás", "sa", "ro"], r: 0 },
        { q: "Qual a sílaba tónica de 'Café'?", o: ["Ca", "Fé"], r: 1 },
        { q: "Sílaba tónica de 'Relógio':", o: ["Re", "Ló", "gio"], r: 1 },
        { q: "Sílaba tónica de 'Médico':", o: ["Mé", "di", "co"], r: 0 },
        { q: "Qual a sílaba tónica de 'Computador'?", o: ["Com", "pu", "ta", "dor"], r: 3 },
        { q: "Qual a sílaba tónica de 'Estrela'?", o: ["Es", "tre", "la"], r: 1 },
        { q: "Sílaba tónica de 'Sapato':", o: ["Sa", "pa", "to"], r: 1 },
        { q: "Na palavra 'Menino', a sílaba tónica é 'ni'. As outras são:", o: ["Átonas", "Tónicas"], r: 0 },
        { q: "A palavra 'Pai' tem quantas sílabas átonas?", o: ["Zero (é monossílabo tónico)", "Uma"], r: 0 },
        { q: "Na palavra 'Sapato', quais são as sílabas átonas?", o: ["'Sa' e 'to'", "'pa'"], r: 0 },
        { q: "A palavra 'Janela' é uma palavra:", o: ["Esdruxular", "Grave", "Aguda"], r: 1 },
        { q: "A palavra 'Jacaré' é uma palavra:", o: ["Aguda", "Grave"], r: 0 },
        { q: "A palavra 'Lâmpada' é:", o: ["Aguda", "Grave", "Esdruxular"], r: 2 },
        { q: "A palavra 'Sofá' é:", o: ["Aguda", "Grave"], r: 0 },
        { q: "A palavra 'Pincel' é uma palavra:", o: ["Aguda", "Grave"], r: 0 },
        { q: "A palavra 'Música' é uma palavra:", o: ["Grave", "Esdruxular"], r: 1 },
        { q: "A palavra 'Rápido' é uma palavra:", o: ["Aguda", "Grave", "Esdruxular"], r: 2 },
        { q: "A palavra 'Chaminé' é uma palavra:", o: ["Aguda", "Grave"], r: 0 },
        { q: "A palavra 'Caderno' é uma palavra:", o: ["Aguda", "Grave"], r: 1 },
        { q: "A palavra 'Boneca' é uma palavra:", o: ["Aguda", "Grave"], r: 1 },

        // --- 2. DIVISÃO SILÁBICA E NÚMERO DE SÍLABAS ---
        { q: "Como se separa a palavra 'Carro' (translineação)?", o: ["Ca-rro", "Car-ro"], r: 1 },
        { q: "Como se separa 'Pássaro'?", o: ["Pás-sa-ro", "Páss-a-ro"], r: 0 },
        { q: "Na separação silábica de 'Passarinho', os 'ss' ficam:", o: ["Juntos", "Separados"], r: 1 },
        { q: "Como se separa a palavra 'Passarinho'?", o: ["Pas-sa-ri-nho", "Pa-ssa-ri-nho"], r: 0 },
        { q: "Quantas sílabas tem 'Borboleta'?", o: ["3", "4", "5"], r: 1 },
        { q: "'Sol' é uma palavra:", o: ["Monossílaba", "Dissílaba"], r: 0 },
        { q: "'Escola' é uma palavra:", o: ["Dissílaba", "Trissílaba"], r: 1 },
        { q: "'Hipopótamo' é uma palavra:", o: ["Trissílaba", "Polissílaba"], r: 1 },
        { q: "A palavra 'Felicidade' é:", o: ["Trissílaba", "Polissílaba"], r: 1 },
        { q: "Quantas sílabas tem 'Arco-íris'?", o: ["2", "4"], r: 1 },

        // --- 3. NOMES (Próprios, Comuns, Coletivos) ---
        { q: "A palavra 'Lisboa' é um nome:", o: ["Comum", "Próprio"], r: 1 },
        { q: "Escolha o nome próprio:", o: ["País", "Portugal"], r: 1 },
        { q: "Qual destas palavras é um nome próprio?", o: ["Porto", "Cidade"], r: 0 },
        { q: "Qual nome é próprio?", o: ["Rio", "Douro"], r: 1 },
        { q: "Qual é um nome comum?", o: ["Maria", "Menina"], r: 1 },
        { q: "O coletivo de 'Peixes' é:", o: ["Cardume", "Alcateia"], r: 0 },
        { q: "O coletivo de 'Ovelhas' é:", o: ["Rebanho", "Matilha"], r: 0 },
        { q: "O coletivo de 'Cães' é:", o: ["Matilha", "Alcateia"], r: 0 },
        { q: "O coletivo de 'Livros' é:", o: ["Biblioteca", "Pinacoteca"], r: 0 },

        // --- 4. GÉNERO E NÚMERO (Masculino/Feminino, Plural) ---
        { q: "Feminino de 'Ator':", o: ["Atriz", "Atora"], r: 0 },
        { q: "Feminino de 'Leão' é:", o: ["Leoa", "Leoaia"], r: 0 },
        { q: "Feminino de 'Cavalo'?", o: ["Égua", "Cavala"], r: 0 },
        { q: "Qual o feminino de 'Cão'?", o: ["Cadela", "Cãozinha"], r: 0 },
        { q: "Qual o feminino de 'Doutor'?", o: ["Doutora", "Doutoraia"], r: 0 },
        { q: "Masculino de 'Galinha':", o: ["Galo", "Frango"], r: 0 },
        { q: "O masculino de 'Ovelha' é:", o: ["Carneiro", "Bode"], r: 0 },
        { q: "Feminino de 'Padrinho'?", o: ["Madrinha", "Mãe"], r: 0 },
        { q: "Qual é o masculino de 'Madrinha'?", o: ["Padrinho", "Pai"], r: 0 },
        { q: "Plural de 'Pão':", o: ["Pães", "Pãos"], r: 0 },
        { q: "Plural de 'Animal':", o: ["Animais", "Animales"], r: 0 },
        { q: "Plural de 'Funil':", o: ["Funis", "Funiles"], r: 0 },
        { q: "Plural de 'Nariz'?", o: ["Narizes", "Narizs"], r: 0 },
        { q: "Plural de 'Jardim'?", o: ["Jardins", "Jardims"], r: 0 },
        { q: "Plural de 'Pai'?", o: ["Pais", "Paes"], r: 0 },
        { q: "O plural de 'Jornal' é:", o: ["Jornais", "Jornals"], r: 0 },
        { q: "O plural de 'Botão' é:", o: ["Botões", "Botãos"], r: 0 },
        { q: "Escolha o plural de 'Lençol':", o: ["Lençóis", "Lençols"], r: 0 },
        { q: "Plural de 'Balão' é:", o: ["Balões", "Balãos"], r: 0 },

        // --- 5. ACENTUAÇÃO E SINAIS GRÁFICOS ---
        { q: "Como se chama o sinal (~) em 'Mão'?", o: ["Acento Agudo", "Til"], r: 1 },
        { q: "Como se chama o sinal por baixo da letra 'c' em 'Moça'?", o: ["Til", "Cedilha"], r: 1 },
        { q: "Qual palavra usa o TIL (~)?", o: ["Maçã", "Música"], r: 0 },
        { q: "A palavra 'Mão' usa o til porque o som é:", o: ["Aberto", "Nasal"], r: 1 },
        { q: "'Árvore' tem acento:", o: ["Agudo (´)", "Circunflexo (^)"], r: 0 },
        { q: "O que indica o acento circunflexo?", o: ["Som aberto", "Som fechado"], r: 1 },
        { q: "Qual palavra tem acento circunflexo?", o: ["Ténis", "Lápis"], r: 0 },
        { q: "O que indica o ponto de exclamação (!)?", o: ["Uma pergunta", "Uma surpresa ou ordem"], r: 1 },
        { q: "O ponto de interrogação (?) serve para:", o: ["Fazer uma pergunta", "Dar uma ordem"], r: 0 },
        { q: "O ponto final (.) serve para:", o: ["Terminar uma frase", "Fazer uma pergunta"], r: 0 },

        // --- 6. SEMÂNTICA E GRAMÁTICA (Antónimos, Sinónimos, Verbos) ---
        { q: "Antónimo de 'Fácil':", o: ["Difícil", "Rápido"], r: 0 },
        { q: "Antónimo de 'Quente'?", o: ["Frio", "Arrefece"], r: 0 },
        { q: "Qual o antónimo de 'Baixo'?", o: ["Alto", "Curto"], r: 0 },
        { q: "Qual o antónimo de 'Novo'?", o: ["Velho", "Moderno"], r: 0 },
        { q: "Antónimo de 'Cheio'?", o: ["Vazio", "Grande"], r: 0 },
        { q: "Qual o antónimo de 'Aparecer'?", o: ["Desaparecer", "Ficar"], r: 0 },
        { q: "Sinónimo de 'Lindo':", o: ["Bonito", "Feio"], r: 0 },
        { q: "Sinónimo de 'Morar'?", o: ["Viver/Residir", "Sair"], r: 0 },
        { q: "Qual o sinónimo de 'Alegre'?", o: ["Contente", "Triste"], r: 0 },
        { q: "Qual destas palavras é um verbo (ação)?", o: ["Saltar", "Salto"], r: 0 },
        { q: "A frase 'Eu comi' está no:", o: ["Pretérito (Passado)", "Futuro"], r: 0 },
        { q: "A frase 'O sol brilha' está no:", o: ["Presente", "Pretérito"], r: 0 },
        { q: "Na frase 'A Maria comeu a maçã', quem é o sujeito?", o: ["A Maria", "A maçã"], r: 0 },

        // --- 7. LEITURA E ESCRITA ---
        { q: "Qual palavra rima com 'Coração'?", o: ["Mão", "Céu"], r: 0 },
        { q: "Qual destas palavras rima com 'Janela'?", o: ["Panela", "Porta"], r: 0 },
        { q: "Aumentativo de 'Casa'?", o: ["Casarão", "Casinha"], r: 0 },
        { q: "Diminutivo de 'Livro'?", o: ["Livrinho", "Livrote"], r: 0 },
        { q: "Qual é o diminutivo de 'Cão'?", o: ["Cãozinho", "Cãozão"], r: 0 },
        { q: "O que é uma 'resposta de construção'?", o: ["Escrever a resposta com as minhas palavras", "Marcar uma cruz"], r: 0 }
    ],
    matematica: [
        // --- 1. NÚMEROS E OPERAÇÕES (Até 399, Dobro, Metade, Pares/Ímpares) ---
        { q: "Qual número vem logo a seguir ao 398?", o: ["397", "399"], r: 1 },
        { q: "Qual o antecessor de 300?", o: ["299", "301"], r: 0 },
        { q: "Qual o número que vem imediatamente antes de 399?", o: ["398", "400"], r: 0 },
        { q: "O número 399 é o sucessor de:", o: ["398", "400"], r: 0 },
        { q: "Qual número está entre 250 e 252?", o: ["251", "253"], r: 0 },
        { q: "Qual o número maior?", o: ["309", "390"], r: 1 },
        { q: "Qual o número par?", o: ["122", "123"], r: 0 },
        { q: "O número 200 termina em 0, por isso é:", o: ["Par", "Ímpar"], r: 0 },
        { q: "Qual o número ímpar?", o: ["350", "351"], r: 1 },
        { q: "O dobro de 150 é:", o: ["300", "200"], r: 0 },
        { q: "Qual número é o dobro de 100?", o: ["200", "150"], r: 0 },
        { q: "A metade de 200 é:", o: ["100", "150"], r: 0 },
        { q: "A metade de 100 é:", o: ["50", "25"], r: 0 },
        { q: "Qual é a metade de 20?", o: ["10", "5"], r: 0 },
        { q: "Como se escreve o número ordinal 5.º?", o: ["Quinto", "Quarto"], r: 0 },
        { q: "Como se escreve o número ordinal 10.º?", o: ["Décimo", "Nono"], r: 0 },
        { q: "Na numeração romana, o que representa o 'V'?", o: ["5", "10"], r: 0 },
        { q: "Na numeração romana, o que representa o 'X'?", o: ["10", "5"], r: 0 },

        // --- 2. DECOMPOSIÇÃO E VALOR POSICIONAL ---
        { q: "3 Centenas + 4 Dezenas + 2 Unidades é:", o: ["342", "243"], r: 0 },
        { q: "3 Centenas + 9 Unidades é o número:", o: ["309", "390"], r: 0 },
        { q: "3 Centenas + 5 Unidades é igual a:", o: ["305", "350"], r: 0 },
        { q: "3 centenas e 2 dezenas formam o número:", o: ["320", "302"], r: 0 },
        { q: "O número 382 tem:", o: ["3 Centenas, 8 Dezenas e 2 Unidades", "3 Dezenas e 8 Unidades"], r: 0 },
        { q: "O número 245 tem quantas dezenas no total?", o: ["24", "4"], r: 0 },
        { q: "Quantas dezenas há numa centena?", o: ["10 dezenas", "100 dezenas"], r: 0 },
        { q: "O número 300 tem quantas dezenas?", o: ["30", "3"], r: 0 },
        { q: "10 dezenas formam:", o: ["1 Centena", "1 Unidade"], r: 0 },
        { q: "O número 100 é uma:", o: ["Centena", "Dezena"], r: 0 },
        { q: "Trezentos e oitenta e cinco escreve-se:", o: ["385", "358"], r: 0 },

        // --- 3. GEOMETRIA E SÓLIDOS (Poliedros e Não Poliedros) ---
        { q: "Os poliedros têm apenas superfícies:", o: ["Planas", "Curvas"], r: 0 },
        { q: "Qual destes sólidos geométricos é um poliedro?", o: ["Cubo", "Esfera"], r: 0 },
        { q: "A pirâmide é um poliedro porque todas as suas faces são:", o: ["Planas", "Curvas"], r: 0 },
        { q: "O cubo tem quantas faces?", o: ["6", "8"], r: 0 },
        { q: "Qual sólido tem 12 arestas e 6 faces quadradas?", o: ["Cubo", "Esfera"], r: 0 },
        { q: "A esfera, o cilindro e o cone são sólidos:", o: ["Não poliedros", "Poliedros"], r: 0 },
        { q: "Quantos vértices tem um triângulo?", o: ["3", "4"], r: 0 },
        { q: "Um retângulo tem quantos lados?", o: ["4", "3"], r: 0 },
        { q: "Se dividires um quadrado ao meio por uma linha, essa linha chama-se:", o: ["Eixo de Simetria", "Vértice"], r: 0 },

        // --- 4. DINHEIRO E MEDIDAS ---
        { q: "Uma moeda de 1€ vale quantos cêntimos?", o: ["100", "50"], r: 0 },
        { q: "Qual destas moedas vale mais?", o: ["50 cêntimos", "20 cêntimos"], r: 0 },
        { q: "Quantas moedas de 50 cêntimos preciso para fazer 2€?", o: ["4", "2"], r: 0 },
        { q: "Tens 2 moedas de 50 cêntimos. Quanto tens no total?", o: ["1 Euro", "2 Euros"], r: 0 },
        { q: "Uma nota de 10€ e duas de 5€ totalizam:", o: ["20€", "15€"], r: 0 },
        { q: "Quanto valem 2 notas de 5€ e 1 moeda de 2€?", o: ["12€", "15€"], r: 0 },
        { q: "Se pagas 2€ por um gelado que custa 1,50€, qual o troco?", o: ["0,50€", "1,00€"], r: 0 },
        { q: "Para medir a massa (peso) de um objeto usamos a:", o: ["Balança", "Régua"], r: 0 },
        { q: "Qual é a unidade principal para medir o comprimento?", o: ["Metro (m)", "Quilo (kg)"], r: 0 },
        { q: "Quantos meses tem um ano?", o: ["12", "10"], r: 0 },

        // --- 5. DADOS E ESTATÍSTICA (Carroll e Frequências) ---
        { q: "O diagrama de Carroll serve para organizar dados por:", o: ["Duas características (ex: cor e forma)", "Ordem de tamanho"], r: 0 },
        { q: "Numa tabela, o que indica a 'frequência absoluta'?", o: ["O número de vezes que um dado aparece", "A cor do gráfico"], r: 0 },
        { q: "Como se chama o gráfico que usa pontos para marcar dados?", o: ["Gráfico de Pontos", "Gráfico de Barras"], r: 0 },
        { q: "Num gráfico de barras, a barra mais pequena representa o valor:", o: ["Menos frequente", "Mais frequente"], r: 0 },

        // --- 6. ITINERÁRIOS E ORIENTAÇÃO NO ESPAÇO ---
        { q: "Num itinerário, o que significa a seta ↑?", o: ["Seguir em frente", "Virar à esquerda"], r: 0 },
        { q: "Rodar 90 graus à direita corresponde a um:", o: ["Quarto de volta", "Meia volta"], r: 0 },
        { q: "Se deres uma 'meia volta', quantos graus rodaste?", o: ["180º", "90º"], r: 0 },
        { q: "Qual o objeto que usamos para saber onde fica o Norte?", o: ["Bússola", "Termómetro"], r: 0 },
        { q: "Se estiveres de frente para o Norte, o Sul fica:", o: ["Atrás de ti", "À tua direita"], r: 0 }
    ],
    estudo_meio: [
        // --- 1. SOCIEDADE, FAMÍLIA E GRUPOS SOCIAIS ---
        { q: "A família e a escola são exemplos de:", o: ["Grupos e comunidades", "Países"], r: 0 },
        { q: "A família nuclear é normalmente formada por:", o: ["Pais e Filhos", "Primos e Vizinhos"], r: 0 },
        { q: "Quem faz parte da tua família alargada?", o: ["Tios, primos e avós", "Colegas de turma"], r: 0 },
        { q: "O teu apelido (nome de família) vem dos teus:", o: ["Pais/Antepassados", "Amigos"], r: 0 },
        { q: "Um grupo social onde vivemos e partilhamos interesses é a:", o: ["Comunidade", "Floresta"], r: 0 },
        { q: "Viver em sociedade exige respeitar:", o: ["Regras e leis", "Apenas o que queremos"], r: 0 },
        { q: "Na escola, todos temos o dever de:", o: ["Respeitar professores e colegas", "Chegar sempre atrasado"], r: 0 },

        // --- 2. DIREITOS E DEVERES DA CRIANÇA ---
        { q: "Toda a criança tem direito a:", o: ["Saúde e Educação", "Trabalhar"], r: 0 },
        { q: "Qual destes é um direito à identidade?", o: ["Ter um Nome e Nacionalidade", "Ter um Computador"], r: 0 },
        { q: "Brincar e descansar é um:", o: ["Direito da criança", "Dever da criança"], r: 0 },
        { q: "Onde estão escritos os direitos das crianças?", o: ["Na Convenção sobre os Direitos da Criança", "No livro de Português"], r: 0 },
        { q: "Um dever importante da criança em casa é:", o: ["Ajudar em pequenas tarefas", "Ver televisão todo o dia"], r: 0 },
        { q: "Os direitos das crianças são iguais para todos?", o: ["Sim, em todo o mundo", "Só em Portugal"], r: 0 },

        // --- 3. PASSADO PESSOAL, FAMILIAR E HISTÓRIA ---
        { q: "O esquema que mostra os nossos antepassados chama-se:", o: ["Árvore Genealógica", "Mapa de Portugal"], r: 0 },
        { q: "Os teus avós paternos são os pais do teu:", o: ["Pai", "Tio"], r: 0 },
        { q: "O teu passado pessoal começou quando:", o: ["Nasceste", "Entraste na escola"], r: 0 },
        { q: "O que celebramos no dia 25 de Abril em Portugal?", o: ["A Liberdade e a Democracia", "A Independência"], r: 0 },
        { q: "Povos como os Romanos e os Árabes influenciaram Portugal?", o: ["Sim, na língua e monumentos", "Não, nunca cá estiveram"], r: 0 },
        { q: "Onde podemos encontrar objetos do passado para estudar?", o: ["Nos Museus", "No Supermercado"], r: 0 },

        // --- 4. PORTUGAL: LOCALIZAÇÃO E GEOGRAFIA ---
        { q: "Portugal fica situado no continente:", o: ["Europeu", "Africano"], r: 0 },
        { q: "Portugal faz parte da Península:", o: ["Ibérica", "Itálica"], r: 0 },
        { q: "Qual o único país que faz fronteira terrestre com Portugal?", o: ["Espanha", "França"], r: 0 },
        { q: "Portugal é banhado por qual oceano?", o: ["Oceano Atlântico", "Oceano Pacífico"], r: 0 },
        { q: "As Regiões Autónomas de Portugal são os arquipélagos da:", o: ["Madeira e Açores", "Canárias"], r: 0 },
        { q: "Qual é a capital de Portugal?", o: ["Lisboa", "Porto"], r: 0 },
        { q: "Qual o rio que nasce em Portugal e é o maior de todos os nacionais?", o: ["Mondego", "Tejo"], r: 0 },
        { q: "Portugal divide-se em distritos, concelhos e:", o: ["Freguesias", "Bairros"], r: 0 },

        // --- 5. SÍMBOLOS, INSTITUIÇÕES E CULTURA ---
        { q: "Quais as cores da Bandeira Nacional de Portugal?", o: ["Verde e Vermelho", "Azul e Branco"], r: 0 },
        { q: "O Hino Nacional de Portugal chama-se:", o: ["A Portuguesa", "Fado"], r: 0 },
        { q: "Qual é a moeda que usamos em Portugal?", o: ["Euro", "Escudo"], r: 0 },
        { q: "Onde reside o Presidente da República?", o: ["Palácio de Belém", "Castelo de S. Jorge"], r: 0 },
        { q: "Quem cuida dos jardins e lixo da nossa localidade?", o: ["A Câmara Municipal / Junta de Freguesia", "O Governo"], r: 0 },
        { q: "O dia de Portugal, de Camões e das Comunidades é:", o: ["10 de Junho", "1 de Dezembro"], r: 0 },
        { q: "O Fado é um estilo de música tradicional de:", o: ["Portugal", "Espanha"], r: 0 },

        // --- 6. NATUREZA, SEGURANÇA E AMBIENTE ---
        { q: "Para atravessar a estrada com segurança, devemos usar:", o: ["A Passadeira", "Qualquer sítio"], r: 0 },
        { q: "O sinal de STOP obriga o condutor a:", o: ["Parar obrigatoriamente", "Andar mais depressa"], r: 0 },
        { q: "As plantas precisam de água, luz e o quê para viver?", o: ["Sais minerais (terra)", "Açúcar"], r: 0 },
        { q: "No ecoponto Verde, devemos colocar:", o: ["Vidro", "Papel"], r: 0 },
        { q: "No ecoponto Amarelo, devemos colocar:", o: ["Plástico e Metal", "Vidro"], r: 0 },
        { q: "No ecoponto Azul, devemos colocar:", o: ["Papel e Cartão", "Plástico"], r: 0 },
        { q: "Qual destes é um meio de comunicação em massa?", o: ["Televisão", "Carta"], r: 0 }
    ]
};